"""Stable public API for the Causal Decision Agent lifecycle."""

from .analysis import analyze_study
from .design import create_study_design
from .schemas import (
    AnalysisOptions,
    CausalContract,
    ColumnMapping,
    DataContract,
    DatasetSnapshot,
    DecisionOutcome,
    DecisionStatus,
    DesignSpec,
    Diagnostic,
    DiagnosticStatus,
    Estimand,
    EventStudyPoint,
    MetricDirection,
    MetricEstimate,
    MetricKind,
    MetricSpec,
    StudyAnalysisResult,
    StudyDesignArtifact,
    StudyDesignRequest,
    StudyDesignType,
    TraceEvent,
    TransformationLogEntry,
)

__all__ = [
    "AnalysisOptions",
    "CausalContract",
    "ColumnMapping",
    "DataContract",
    "DatasetSnapshot",
    "DecisionOutcome",
    "DecisionStatus",
    "DesignSpec",
    "Diagnostic",
    "DiagnosticStatus",
    "Estimand",
    "EventStudyPoint",
    "MetricDirection",
    "MetricEstimate",
    "MetricKind",
    "MetricSpec",
    "StudyAnalysisResult",
    "StudyDesignArtifact",
    "StudyDesignRequest",
    "StudyDesignType",
    "TraceEvent",
    "TransformationLogEntry",
    "analyze_study",
    "create_study_design",
]
